using AshkanCRM.Models;
namespace AshkanCRM.Services;
public class CrmStore {
 public List<CrmUser> Users {get;}=[new(1,"مدیر سیستم","admin@ashkancrm.local","Admin123!",Roles.Admin,"مدیریت","AM"),new(2,"سارا احمدی","sales@ashkancrm.local","Sales123!",Roles.SalesManager,"فروش","SA"),new(3,"علی رضایی","support@ashkancrm.local","Support123!",Roles.Support,"پشتیبانی","AR"),new(4,"مریم کریمی","marketing@ashkancrm.local","Marketing123!",Roles.Marketing,"بازاریابی","MK")];
 public List<Customer> Customers {get;}=[new(1,"آرمان محمدی","فناوری سپهر","arman@sepehr.ir","021-88771230","Enterprise","سارا احمدی","فعال",92),new(2,"نیلوفر یوسفی","راهکار نوین","niloufar@novin.ir","021-44559120","SMB","رضا حیدری","فعال",78),new(3,"کاوه اکبری","پارس داده","kaveh@parsdata.ir","026-32211009","Enterprise","سارا احمدی","سرنخ",85),new(4,"مهسا مرادی","آتیه سازان","mahsa@atieh.ir","021-22003456","Mid-market","رضا حیدری","فعال",71),new(5,"امیر حسین پور","ابر شرق","amir@abrshargh.ir","051-37650012","SMB","سارا احمدی","غیرفعال",54)];
 public List<Deal> Deals {get;}=[new(1,"تمدید CRM سازمانی","فناوری سپهر","سارا احمدی",1850000000,"مذاکره",75,"1405/08/15"),new(2,"استقرار تیم فروش","پارس داده","سارا احمدی",980000000,"پیشنهاد",55,"1405/08/28"),new(3,"پکیج پشتیبانی طلایی","راهکار نوین","رضا حیدری",420000000,"بررسی",35,"1405/09/05"),new(4,"اتوماسیون بازاریابی","آتیه سازان","رضا حیدری",760000000,"برنده",100,"1405/07/20")];
 public List<TaskItem> Tasks {get;}=[new(1,"پیگیری پروپوزال پارس داده","سارا احمدی","بالا","امروز 14:30","باز","تماس"),new(2,"دموی نسخه Enterprise","رضا حیدری","متوسط","فردا 10:00","باز","جلسه"),new(3,"بررسی تیکت SLA","علی رضایی","فوری","امروز 12:00","درحال انجام","پشتیبانی"),new(4,"کمپین مشتریان غیرفعال","مریم کریمی","متوسط","شنبه","باز","کمپین")];
 public List<Ticket> Tickets {get;}=[new(1048,"خطا در همگام‌سازی مخاطبین","فناوری سپهر","فوری","باز","علی رضایی","12 دقیقه قبل"),new(1047,"درخواست گزارش سفارشی","راهکار نوین","متوسط","درحال بررسی","علی رضایی","1 ساعت قبل"),new(1046,"راهنمای API","آتیه سازان","کم","حل شده","نگار حسینی","دیروز")];
 public List<Lead> Leads {get;}=[new(1,"پویان مرادی","داده گستر","LinkedIn","سارا احمدی","واجد شرایط",88,"امروز"),new(2,"شیوا رضایی","هوشمند افزار","Website","سارا احمدی","جدید",72,"دیروز"),new(3,"نوید اکبری","فراز سیستم","Referral","رضا حیدری","در حال پیگیری",81,"2 روز قبل"),new(4,"سمانه کریمی","راهکار شرق","Campaign","رضا حیدری","جدید",64,"3 روز قبل")];
 public List<ActivityItem> Activities {get;}=[new(1,"جلسه","دموی محصول Enterprise","فناوری سپهر","سارا احمدی","امروز 15:00","برنامه‌ریزی شده"),new(2,"تماس","پیگیری قرارداد","پارس داده","سارا احمدی","فردا 09:30","برنامه‌ریزی شده"),new(3,"ایمیل","ارسال پیشنهاد قیمت","راهکار نوین","رضا حیدری","دیروز","انجام شده")];
 public List<NotificationItem> Notifications {get;}=[new(1,"فرصت فروش نیازمند پیگیری","قرارداد پارس داده 3 روز بدون فعالیت است.","10 دقیقه قبل",false,"Sales"),new(2,"SLA در معرض نقض","تیکت #1048 کمتر از 30 دقیقه تا SLA دارد.","18 دقیقه قبل",false,"Support"),new(3,"کمپین آماده انتشار","کمپین مشتریان غیرفعال آماده بازبینی است.","1 ساعت قبل",true,"Marketing")];
 public List<AuditItem> Audit {get;}=[new(1,"مدیر سیستم","ورود","Authentication","ورود موفق به سامانه","امروز 08:42"),new(2,"سارا احمدی","ویرایش","Deal #2","احتمال موفقیت از 45٪ به 55٪ تغییر کرد","امروز 09:10"),new(3,"علی رضایی","تغییر وضعیت","Ticket #1047","وضعیت به درحال بررسی تغییر کرد","امروز 10:05")];

 public List<ProductItem> Products {get;}=[new(1,"CRM Enterprise","CRM-ENT","Software",240000000,"فعال",999),new(2,"Support Gold","SUP-GOLD","Service",78000000,"فعال",999),new(3,"Marketing Automation","MKT-AUTO","Add-on",125000000,"فعال",999),new(4,"Onboarding Pack","ONB-PRO","Service",45000000,"فعال",999)];
 public List<QuoteItem> Quotes {get;}=[new(1,"Q-1405-091","فناوری سپهر","سارا احمدی",1850000000,"ارسال شده","1405/08/20"),new(2,"Q-1405-092","پارس داده","سارا احمدی",980000000,"پیش‌نویس","1405/08/28"),new(3,"Q-1405-087","راهکار نوین","رضا حیدری",420000000,"تایید شده","1405/08/10")];
 public List<AutomationRule> Automations {get;}=[new(1,"Follow-up hot leads","Lead score > 80","Create task + notify owner","Sales Manager",true,126),new(2,"SLA escalation","Ticket SLA < 30m","Notify support lead","Support",true,42),new(3,"Dormant customer nurture","No activity for 30 days","Add to nurture campaign","Marketing",true,78),new(4,"Won deal onboarding","Deal becomes Won","Create onboarding checklist","Admin",false,19)];
 public List<KnowledgeArticle> Knowledge {get;}=[new(1,"Enterprise onboarding checklist","Sales","سارا احمدی","امروز",438,"منتشر شده"),new(2,"API integration guide","Technical","علی رضایی","دیروز",812,"منتشر شده"),new(3,"SLA escalation playbook","Support","علی رضایی","3 روز قبل",296,"منتشر شده"),new(4,"Lead qualification framework","Sales","مدیر سیستم","هفته قبل",521,"پیش‌نویس")];
 public List<GoalItem> Goals {get;}=[new(1,"سارا احمدی","Revenue",2200000000,1850000000,"ماه جاری"),new(2,"رضا حیدری","Revenue",1600000000,1180000000,"ماه جاری"),new(3,"تیم فروش","Qualified Leads",40,31,"ماه جاری")];
 public List<ContactItem> Contacts {get;}=[new(1,1,"الهام شریفی","مدیر فناوری","elham@sepehr.ir","021-88771231",true),new(2,1,"میلاد توکلی","مدیر خرید","milad@sepehr.ir","021-88771232",false),new(3,2,"فرهاد احمدی","مدیرعامل","farhad@novin.ir","021-44559121",true)];
 public List<NoteItem> Notes {get;}=[new(1,1,"سارا احمدی","مشتری به ماژول Automation و SSO علاقه‌مند است.","امروز 11:20","Team"),new(2,1,"مدیر سیستم","ریسک تمدید پایین؛ رضایت پشتیبانی بالا است.","دیروز","Managers")];
 public List<PermissionItem> Permissions {get;}=[new(Roles.Admin,"All modules",true,true,true,true,true),new(Roles.SalesManager,"Sales & reports",true,true,true,true,true),new(Roles.Sales,"Own sales workspace",true,true,true,false,true),new(Roles.Support,"Support & knowledge",true,true,true,false,false),new(Roles.Marketing,"Marketing & leads",true,true,true,false,true)];
 public List<ImportJob> Imports {get;}=[new(1,"customers-september.csv","Customers","مدیر سیستم","Completed",420,416,4,"امروز 09:14"),new(2,"linkedin-leads.xlsx","Leads","مریم کریمی","Completed",186,181,5,"دیروز 16:40")];
 public List<ApiKeyItem> ApiKeys {get;}=[new(1,"BI Connector","crm_live_7K...","reports:read","مدیر سیستم","2 دقیقه قبل","فعال"),new(2,"Marketing Sync","crm_live_M2...","leads:write","مریم کریمی","1 ساعت قبل","فعال")];

 public List<TeamItem> Teams {get;}=[new(1,"Enterprise Sales","فروش","سارا احمدی",6,"Enterprise accounts","فعال"),new(2,"SMB Sales","فروش","رضا حیدری",5,"SMB & inbound","فعال"),new(3,"Customer Care","پشتیبانی","علی رضایی",7,"Tickets & SLA","فعال"),new(4,"Growth","بازاریابی","مریم کریمی",4,"Campaigns & lifecycle","فعال")];
 public List<ApprovalItem> Approvals {get;}=[new(1,"تخفیف 18٪ برای فناوری سپهر","Quote Discount","سارا احمدی","مدیر فروش","امروز 11:20","در انتظار","بالا"),new(2,"فعال‌سازی API Key جدید","Security","مریم کریمی","Admin","امروز 09:45","در انتظار","متوسط"),new(3,"تغییر مالک Deal پارس داده","Ownership","رضا حیدری","مدیر فروش","دیروز","تایید شده","متوسط")];
 public List<SessionItem> Sessions {get;}=[new(1,"مدیر سیستم","Chrome / Windows","Tehran","192.168.1.20","همین حالا","فعال"),new(2,"سارا احمدی","Edge / Windows","Tehran","192.168.1.44","8 دقیقه قبل","فعال"),new(3,"علی رضایی","Chrome / Android","Karaj","10.0.0.18","35 دقیقه قبل","فعال")];
 public List<AiInsightItem> AiInsights {get;}=[new(1,"Sales","Deal فناوری سپهر آماده اقدام است","احتمال موفقیت بالا است اما آخرین تعامل باید به جلسه تصمیم‌گیری تبدیل شود.","High","جلسه تصمیم‌گیری ایجاد کن","Sales"),new(2,"Support","ریسک SLA در Ticket #1048","زمان پاسخ باقی‌مانده کم است و اولویت فوری دارد.","Critical","به Support Lead ارجاع بده","Support"),new(3,"Marketing","Leadهای LinkedIn کیفیت بالاتری دارند","میانگین Score سرنخ‌های LinkedIn از سایر منابع بالاتر است.","Medium","بودجه کمپین را بازبینی کن","Marketing"),new(4,"Admin","بازبینی دسترسی کاربران توصیه می‌شود","حساب‌های فعال و نقش‌ها را در بازبینی دوره‌ای دسترسی بررسی کنید.","Medium","Access Review اجرا کن","Admin")];
 public List<FeatureFlagItem> FeatureFlags {get;}=[new(1,"ai.copilot","AI Copilot",true,"All authenticated users","Admin"),new(2,"sales.approvals","Sales approvals",true,"SalesManager,Admin","Admin"),new(3,"security.sessions","Session center",true,"Admin","Admin"),new(4,"beta.smart_scoring","Smart scoring beta",false,"SalesManager","Admin")];

 public List<UserPermissionGrant> UserPermissions {get;}=[new(1,"sales@ashkancrm.local","Customers",true,true,true,false,true,false,"Team","مدیر سیستم","امروز"),new(2,"sales@ashkancrm.local","Deals",true,true,true,false,true,true,"Team","مدیر سیستم","امروز"),new(3,"support@ashkancrm.local","Tickets",true,true,true,false,false,false,"All","مدیر سیستم","دیروز"),new(4,"marketing@ashkancrm.local","Leads",true,true,true,false,true,false,"All","مدیر سیستم","دیروز")];
 public List<SmartScoreItem> SmartScores {get;}=[new(1,"Lead","پویان مرادی / داده گستر",91,"Hot","تعامل اخیر + منبع LinkedIn + تناسب سازمانی","جلسه Discovery رزرو شود"),new(2,"Deal","تمدید CRM سازمانی",86,"High","احتمال 75٪ و ارزش بالا","جلسه تصمیم‌گیری تنظیم شود"),new(3,"Customer","فناوری سپهر",94,"Healthy","تعامل پایدار و تیکت‌های کنترل‌شده","Upsell Automation بررسی شود")];
 public List<DuplicateCandidate> Duplicates {get;}=[new(1,"Customer","فناوری سپهر","فناوری سپهر (قدیمی)",96,"نیازمند بررسی"),new(2,"Lead","شیوا رضایی","Shiva Rezaei",88,"نیازمند بررسی")];
 public List<WebhookDelivery> WebhookDeliveries {get;}=[new(1,"ERP Connector","deal.won","200 OK",1,"2 دقیقه قبل"),new(2,"Marketing Sync","lead.updated","200 OK",1,"18 دقیقه قبل"),new(3,"BI Warehouse","customer.changed","Retrying",2,"25 دقیقه قبل")];
 public List<SavedViewItem> SavedViews {get;}=[new(1,"فرصت‌های پرریسک","Deals","سارا احمدی","Probability < 60% AND Value > 500M",true),new(2,"SLA فوری","Tickets","علی رضایی","Priority = Urgent AND Status != Resolved",true),new(3,"Hot Leads","Leads","مریم کریمی","Score >= 80",false)];

 public List<AiAgentItem> AiAgents {get;}=[new(1,"Sales Copilot","Deal risk, follow-up and next-best-action","Sales","Advisory","Active",248,"2 min ago"),new(2,"Support Copilot","Ticket summary, SLA risk and suggested reply","Support","Advisory","Active",391,"5 min ago"),new(3,"Admin Copilot","Access review, security and data-quality signals","Admin","Read-only","Active",84,"18 min ago"),new(4,"Marketing Copilot","Lead segments and campaign insights","Marketing","Advisory","Paused",126,"Yesterday")];
 public List<PlaybookItem> Playbooks {get;}=[new(1,"Enterprise Discovery","Deals","Qualified enterprise lead","6 steps","Sales Manager","Published",82),new(2,"SLA Rescue","Tickets","SLA remaining < 30m","4 steps","Support","Published",91),new(3,"Dormant Customer Win-back","Customers","No activity for 30 days","5 steps","Marketing","Draft",44)];
 public List<SlaPolicyItem> SlaPolicies {get;}=[new(1,"Critical Support","Priority = Urgent","15 min","4 hours","Support Lead → Admin","Active"),new(2,"Enterprise Support","Segment = Enterprise","30 min","8 hours","Support Lead","Active"),new(3,"Standard Support","All other tickets","2 hours","2 business days","Queue Manager","Active")];
 public List<DashboardWidgetItem> DashboardWidgets {get;}=[new(1,"Pipeline Health","Sales","Sales,SalesManager",true,"Large"),new(2,"SLA Risk","Support","Support,Admin",true,"Medium"),new(3,"Access Health","Security","Admin",true,"Medium"),new(4,"Campaign ROI","Marketing","Marketing,Admin",true,"Medium")];

}
