using AshkanCRM.Models;using AshkanCRM.Models.Identity;using AshkanCRM.Data;using Microsoft.EntityFrameworkCore;using AshkanCRM.Services;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Identity;using Microsoft.AspNetCore.Mvc;using System.Text;
namespace AshkanCRM.Controllers;
[Authorize] public class CRMController(CrmStore store, CrmDbContext db, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager):Controller{
 public IActionResult Dashboard(){ViewBag.Customers=store.Customers.Count;ViewBag.Pipeline=store.Deals.Where(x=>x.Stage!="برنده").Sum(x=>x.Value);ViewBag.Won=store.Deals.Where(x=>x.Stage=="برنده").Sum(x=>x.Value);ViewBag.Tasks=store.Tasks.Count(x=>x.Status!="انجام شده");ViewBag.Leads=store.Leads.Count;ViewBag.Notifications=store.Notifications.Count(x=>!x.IsRead);return View(store.Deals);}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> Customers(string? q=null,string? status=null,int page=1){
  const int size=10; page=Math.Max(1,page); var access=await GetAccessAsync(); var query=ApplyScope(db.CrmCustomers.AsNoTracking(),access); if(!string.IsNullOrWhiteSpace(q)) query=query.Where(x=>x.Name.Contains(q)||x.Company.Contains(q)||x.Email.Contains(q)); if(!string.IsNullOrWhiteSpace(status)) query=query.Where(x=>x.Status==status);
  ViewBag.Total=await query.CountAsync(); ViewBag.Page=page;ViewBag.PageSize=size;ViewBag.Query=q;ViewBag.Status=status; var rows=await query.OrderByDescending(x=>x.UpdatedAtUtc).Skip((page-1)*size).Take(size).Select(x=>new Customer(x.Id,x.Name,x.Company,x.Email,x.Phone,x.Segment,x.Owner,x.Status,x.Score)).ToListAsync();return View(rows);
 }
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> CreateCustomer(CustomerEntity input){ModelState.Remove(nameof(input.RowVersion));if(!ModelState.IsValid){TempData["Error"]="Invalid customer data.";return RedirectToAction(nameof(Customers));}input.Id=0;input.CreatedBy=input.UpdatedBy=User.Identity?.Name;input.CreatedAtUtc=input.UpdatedAtUtc=DateTime.UtcNow;if(!User.IsInRole(Roles.Admin)&&!User.IsInRole(Roles.SalesManager))input.Owner=User.Identity?.Name??"";input.TeamKey=await ResolveTeamKey(input.Owner);db.CrmCustomers.Add(input);await db.SaveChangesAsync();await WriteAudit("Create","Customer",input.Id.ToString(),input.Company);await AddActivity("Customer",input.Id,"Created","Customer created",input.Company);TempData["Success"]="Customer created.";return RedirectToAction(nameof(Customers));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> UpdateCustomer(CustomerEntity input){var row=await db.CrmCustomers.FirstOrDefaultAsync(x=>x.Id==input.Id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();row.Name=input.Name;row.Company=input.Company;row.Email=input.Email;row.Phone=input.Phone;row.Segment=input.Segment;row.Status=input.Status;row.Score=input.Score;if(User.IsInRole(Roles.Admin)||User.IsInRole(Roles.SalesManager)){row.Owner=input.Owner;row.TeamKey=await ResolveTeamKey(input.Owner);}row.UpdatedAtUtc=DateTime.UtcNow;row.UpdatedBy=User.Identity?.Name;await db.SaveChangesAsync();await WriteAudit("Update","Customer",row.Id.ToString(),row.Company);await AddActivity("Customer",row.Id,"Updated","Customer updated",row.Company);return RedirectToAction(nameof(Customers));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> DeleteCustomer(int id){var row=await db.CrmCustomers.FirstOrDefaultAsync(x=>x.Id==id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();row.IsDeleted=true;row.UpdatedAtUtc=DateTime.UtcNow;row.UpdatedBy=User.Identity?.Name;await db.SaveChangesAsync();await WriteAudit("SoftDelete","Customer",id.ToString(),row.Company);return RedirectToAction(nameof(Customers));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public async Task<IActionResult> CustomerRecycleBin()=>View(await db.CrmCustomers.IgnoreQueryFilters().AsNoTracking().Where(x=>x.IsDeleted).OrderByDescending(x=>x.UpdatedAtUtc).ToListAsync());
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> RestoreCustomer(int id){var row=await db.CrmCustomers.IgnoreQueryFilters().FirstOrDefaultAsync(x=>x.Id==id&&x.IsDeleted);if(row==null)return NotFound();row.IsDeleted=false;row.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync();await WriteAudit("Restore","Customer",id.ToString(),row.Company);return RedirectToAction(nameof(CustomerRecycleBin));}
 private bool CanManage(string owner)=>User.IsInRole(Roles.Admin)||User.IsInRole(Roles.SalesManager)||string.Equals(owner,User.Identity?.Name,StringComparison.OrdinalIgnoreCase);
 private async Task AddActivity(string entity,int id,string type,string subject,string detail){db.CrmActivities.Add(new ActivityEntity{EntityType=entity,EntityId=id,Type=type,Subject=subject,Detail=detail,Owner=User.Identity?.Name??"system",CreatedBy=User.Identity?.Name});await db.SaveChangesAsync();}
 private async Task WriteAudit(string action,string entity,string entityId,string detail){db.CrmAuditEvents.Add(new AuditEventEntity{Actor=User.Identity?.Name??"system",Action=action,EntityType=entity,EntityId=entityId,Detail=detail,CreatedBy=User.Identity?.Name});await db.SaveChangesAsync();}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> Leads(){var access=await GetAccessAsync();var q=ApplyScope(db.CrmLeads.AsNoTracking(),access);var rows=await q.OrderByDescending(x=>x.Score).Select(x=>new Lead(x.Id,x.Name,x.Company,x.Source,x.Owner,x.Status,x.Score,x.LastContact)).ToListAsync();return View(rows);}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> CreateLead(LeadEntity input){if(!ModelState.IsValid){TempData["Error"]="Invalid lead data.";return RedirectToAction(nameof(Leads));}input.Id=0;input.CreatedBy=input.UpdatedBy=User.Identity?.Name;input.Owner=(User.IsInRole(Roles.Admin)||User.IsInRole(Roles.SalesManager))?input.Owner:(User.Identity?.Name??"");input.TeamKey=await ResolveTeamKey(input.Owner);db.CrmLeads.Add(input);await db.SaveChangesAsync();await WriteAudit("Create","Lead",input.Id.ToString(),input.Company);return RedirectToAction(nameof(Leads));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> Deals(){var access=await GetAccessAsync();var q=ApplyScope(db.CrmDeals.AsNoTracking(),access);var rows=await q.OrderByDescending(x=>x.Value).Select(x=>new Deal(x.Id,x.Title,x.Customer,x.Owner,x.Value,x.Stage,x.Probability,x.CloseDate)).ToListAsync();return View(rows);}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> CreateDeal(DealEntity input){if(!ModelState.IsValid){TempData["Error"]="Invalid deal data.";return RedirectToAction(nameof(Deals));}input.Id=0;input.CreatedBy=input.UpdatedBy=User.Identity?.Name;input.Owner=(User.IsInRole(Roles.Admin)||User.IsInRole(Roles.SalesManager))?input.Owner:(User.Identity?.Name??"");input.TeamKey=await ResolveTeamKey(input.Owner);db.CrmDeals.Add(input);await db.SaveChangesAsync();await WriteAudit("Create","Deal",input.Id.ToString(),input.Customer);return RedirectToAction(nameof(Deals));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> UpdateLead(LeadEntity input){var row=await db.CrmLeads.FirstOrDefaultAsync(x=>x.Id==input.Id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();row.Name=input.Name;row.Company=input.Company;row.Source=input.Source;row.Status=input.Status;row.Score=input.Score;row.LastContact=input.LastContact;if(User.IsInRole(Roles.Admin)||User.IsInRole(Roles.SalesManager)){row.Owner=input.Owner;row.TeamKey=await ResolveTeamKey(input.Owner);}row.UpdatedAtUtc=DateTime.UtcNow;row.UpdatedBy=User.Identity?.Name;await db.SaveChangesAsync();await WriteAudit("Update","Lead",row.Id.ToString(),row.Company);await AddActivity("Lead",row.Id,"Updated","Lead updated",row.Company);return RedirectToAction(nameof(Leads));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> DeleteLead(int id){var row=await db.CrmLeads.FirstOrDefaultAsync(x=>x.Id==id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();row.IsDeleted=true;row.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync();await WriteAudit("SoftDelete","Lead",id.ToString(),row.Company);return RedirectToAction(nameof(Leads));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> UpdateDeal(DealEntity input){var row=await db.CrmDeals.FirstOrDefaultAsync(x=>x.Id==input.Id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();row.Title=input.Title;row.Customer=input.Customer;row.Value=input.Value;row.Stage=input.Stage;row.Probability=input.Probability;row.CloseDate=input.CloseDate;if(User.IsInRole(Roles.Admin)||User.IsInRole(Roles.SalesManager)){row.Owner=input.Owner;row.TeamKey=await ResolveTeamKey(input.Owner);}row.UpdatedAtUtc=DateTime.UtcNow;row.UpdatedBy=User.Identity?.Name;await db.SaveChangesAsync();await WriteAudit("Update","Deal",row.Id.ToString(),row.Title);await AddActivity("Deal",row.Id,"Updated","Deal updated",row.Stage);return RedirectToAction(nameof(Deals));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> MoveDealStage(int id,string stage){var allowed=new[]{"Qualification","Proposal","Negotiation","Won","Lost"};if(!allowed.Contains(stage))return BadRequest();var row=await db.CrmDeals.FirstOrDefaultAsync(x=>x.Id==id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();var old=row.Stage;row.Stage=stage;row.Probability=stage switch{"Qualification"=>20,"Proposal"=>50,"Negotiation"=>75,"Won"=>100,"Lost"=>0,_=>row.Probability};row.ClosedAtUtc=(stage=="Won"||stage=="Lost")?DateTime.UtcNow:null;row.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync();await WriteAudit("StageChange","Deal",id.ToString(),old+" -> "+stage);await AddActivity("Deal",id,"StageChange","Pipeline stage changed",old+" -> "+stage);db.CrmNotifications.Add(new NotificationEntity{UserName=row.Owner,Type="Deal",Title="Pipeline updated",Message=row.Title+": "+old+" → "+stage,CreatedBy=User.Identity?.Name});await db.SaveChangesAsync();return RedirectToAction(nameof(Deals));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> DeleteDeal(int id){var row=await db.CrmDeals.FirstOrDefaultAsync(x=>x.Id==id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();row.IsDeleted=true;row.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync();await WriteAudit("SoftDelete","Deal",id.ToString(),row.Title);return RedirectToAction(nameof(Deals));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> LeadTimeline(int id){var row=await db.CrmLeads.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();ViewBag.EntityTitle=row.Name+" · "+row.Company;ViewBag.EntityType="Lead";ViewBag.EntityId=id;return View("EntityTimeline",await db.CrmActivities.AsNoTracking().Where(x=>x.EntityType=="Lead"&&x.EntityId==id).OrderByDescending(x=>x.OccurredAtUtc).ToListAsync());}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> DealTimeline(int id){var row=await db.CrmDeals.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id);if(row==null)return NotFound();if(!await CanManageScoped(row.Owner,row.TeamKey))return Forbid();ViewBag.EntityTitle=row.Title;ViewBag.EntityType="Deal";ViewBag.EntityId=id;return View("EntityTimeline",await db.CrmActivities.AsNoTracking().Where(x=>x.EntityType=="Deal"&&x.EntityId==id).OrderByDescending(x=>x.OccurredAtUtc).ToListAsync());}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> AddEntityActivity(string entityType,int entityId,string subject,string detail){if(entityType!="Lead"&&entityType!="Deal"&&entityType!="Customer")return BadRequest();await AddActivity(entityType,entityId,"Note",subject,detail);return RedirectToAction(entityType=="Lead"?nameof(LeadTimeline):entityType=="Deal"?nameof(DealTimeline):nameof(CustomerTimeline),new{id=entityId});}

 public async Task<IActionResult> Tasks(){await ProcessDueReminders();var access=await GetAccessAsync();var q=ApplyScope(db.CrmTasks.AsNoTracking().Where(x=>!x.IsDeleted),access);return View(await q.OrderBy(x=>x.Status=="Done").ThenBy(x=>x.DueAtUtc).ToListAsync());}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> CreateTask(CrmTaskEntity input){if(string.IsNullOrWhiteSpace(input.Title))return RedirectToAction(nameof(Tasks));input.Id=0;input.CreatedBy=input.UpdatedBy=User.Identity?.Name;if(!User.IsInRole(Roles.Admin)&&!User.IsInRole(Roles.SalesManager))input.Assignee=User.Identity?.Name??"";input.TeamKey=await ResolveTeamKey(input.Assignee);db.CrmTasks.Add(input);await db.SaveChangesAsync();await WriteAudit("Create","Task",input.Id.ToString(),input.Title);return RedirectToAction(nameof(Tasks));}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> ToggleTask(int id){var t=await db.CrmTasks.FirstOrDefaultAsync(x=>x.Id==id);if(t==null)return NotFound();if(!await CanManageScoped(t.Assignee,t.TeamKey))return Forbid();var completing=t.Status!="Done";t.Status=completing?"Done":"Open";t.UpdatedAtUtc=DateTime.UtcNow;if(completing&&t.IsRecurring&&t.Recurrence!="None"){var nextDue=t.Recurrence switch{"Daily"=>t.DueAtUtc.AddDays(1),"Weekly"=>t.DueAtUtc.AddDays(7),"Monthly"=>t.DueAtUtc.AddMonths(1),_=>t.DueAtUtc.AddDays(1)};db.CrmTasks.Add(new CrmTaskEntity{Title=t.Title,Type=t.Type,Assignee=t.Assignee,TeamKey=t.TeamKey,Priority=t.Priority,Status="Open",DueAtUtc=nextDue,ReminderAtUtc=t.ReminderAtUtc.HasValue?nextDue-(t.DueAtUtc-t.ReminderAtUtc.Value):null,RelatedEntityType=t.RelatedEntityType,RelatedEntityId=t.RelatedEntityId,Description=t.Description,IsRecurring=true,Recurrence=t.Recurrence,CreatedBy=User.Identity?.Name});}await db.SaveChangesAsync();await WriteAudit("StatusChange","Task",id.ToString(),t.Status);return RedirectToAction(nameof(Tasks));}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> DeleteTask(int id){var t=await db.CrmTasks.FirstOrDefaultAsync(x=>x.Id==id);if(t==null)return NotFound();if(!await CanManageScoped(t.Assignee,t.TeamKey))return Forbid();t.IsDeleted=true;t.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync();return RedirectToAction(nameof(Tasks));}
 public IActionResult Activities()=>View(store.Activities);
 public async Task<IActionResult> Calendar(){var q=db.CrmTasks.AsNoTracking().Where(x=>!x.IsDeleted);if(!User.IsInRole(Roles.Admin)&&!User.IsInRole(Roles.SalesManager))q=q.Where(x=>x.Assignee==User.Identity!.Name);return View(await q.OrderBy(x=>x.DueAtUtc).Take(100).ToListAsync());}
 public async Task<IActionResult> GlobalSearch(string q){q=(q??"").Trim();ViewBag.Query=q;var result=new GlobalSearchVm();if(q.Length>=2){var access=await GetAccessAsync();var customers=ApplyScope(db.CrmCustomers.AsNoTracking(),access);var leads=ApplyScope(db.CrmLeads.AsNoTracking(),access);var deals=ApplyScope(db.CrmDeals.AsNoTracking(),access);result.Customers=await customers.Where(x=>x.Name.Contains(q)||x.Company.Contains(q)||x.Email.Contains(q)).Take(8).ToListAsync();result.Leads=await leads.Where(x=>x.Name.Contains(q)||x.Company.Contains(q)).Take(8).ToListAsync();result.Deals=await deals.Where(x=>x.Title.Contains(q)||x.Customer.Contains(q)).Take(8).ToListAsync();}return View(result);}
 public async Task<IActionResult> Notifications(){var u=User.Identity?.Name??"";return View("SqlNotifications",await db.CrmNotifications.AsNoTracking().Where(x=>x.UserName==u||User.IsInRole(Roles.Admin)).OrderByDescending(x=>x.CreatedAtUtc).Take(100).ToListAsync());}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> MarkNotificationRead(int id){var u=User.Identity?.Name??"";var n=await db.CrmNotifications.FirstOrDefaultAsync(x=>x.Id==id&&(x.UserName==u||User.IsInRole(Roles.Admin)));if(n==null)return NotFound();n.IsRead=true;n.ReadAtUtc=DateTime.UtcNow;await db.SaveChangesAsync();return RedirectToAction(nameof(Notifications));}
 [Authorize(Roles=Roles.Admin+","+Roles.Support)] public IActionResult Tickets()=>View(store.Tickets);
 [Authorize(Roles=Roles.Admin+","+Roles.Marketing)] public IActionResult Marketing()=>View();
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public IActionResult Reports()=>View();
 [Authorize(Roles=Roles.Admin)] public async Task<IActionResult> Users(){
  var rows=new List<UserAdminRow>();
  foreach(var u in userManager.Users.OrderByDescending(x=>x.CreatedAtUtc).ToList()) rows.Add(new UserAdminRow{Id=u.Id,Name=u.DisplayName,Email=u.Email??"",Department=u.Department,Initials=u.Initials,IsActive=u.IsActive,IsLocked=u.LockoutEnd>DateTimeOffset.UtcNow,LastLoginAtUtc=u.LastLoginAtUtc,Roles=await userManager.GetRolesAsync(u)});
  ViewBag.Roles=roleManager.Roles.Select(x=>x.Name!).ToList(); return View(rows);
 }
 [Authorize(Roles=Roles.Admin),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> CreateUser(CreateUserVm vm){
  if(!ModelState.IsValid){TempData["Error"]="اطلاعات کاربر کامل یا معتبر نیست.";return RedirectToAction(nameof(Users));}
  if(await userManager.FindByEmailAsync(vm.Email)!=null){TempData["Error"]="این ایمیل قبلاً ثبت شده است.";return RedirectToAction(nameof(Users));}
  var initials=string.Concat(vm.Name.Split(' ',StringSplitOptions.RemoveEmptyEntries).Take(2).Select(x=>x[0]));
  var u=new ApplicationUser{UserName=vm.Email,Email=vm.Email,EmailConfirmed=true,DisplayName=vm.Name,Department=vm.Department,Initials=initials,IsActive=vm.IsActive};
  var result=await userManager.CreateAsync(u,vm.Password); if(!result.Succeeded){TempData["Error"]=string.Join(" | ",result.Errors.Select(x=>x.Description));return RedirectToAction(nameof(Users));}
  if(await roleManager.RoleExistsAsync(vm.Role)) await userManager.AddToRoleAsync(u,vm.Role); TempData["Success"]="کاربر با موفقیت ایجاد شد.";return RedirectToAction(nameof(Users));
 }
 [Authorize(Roles=Roles.Admin),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> UpdateUser(EditUserVm vm){
  var u=await userManager.FindByIdAsync(vm.Id);if(u==null)return NotFound(); if(u.Email=="admin@ashkancrm.local"&&!vm.IsActive){TempData["Error"]="حساب مدیر اصلی قابل غیرفعال‌سازی نیست.";return RedirectToAction(nameof(Users));}
  u.DisplayName=vm.Name;u.Department=vm.Department;u.IsActive=vm.IsActive;u.Initials=string.Concat(vm.Name.Split(' ',StringSplitOptions.RemoveEmptyEntries).Take(2).Select(x=>x[0]));await userManager.UpdateAsync(u);
  var current=await userManager.GetRolesAsync(u);if(current.Count>0)await userManager.RemoveFromRolesAsync(u,current);if(await roleManager.RoleExistsAsync(vm.Role))await userManager.AddToRoleAsync(u,vm.Role);await userManager.UpdateSecurityStampAsync(u);TempData["Success"]="کاربر و سطح دسترسی بروزرسانی شد.";return RedirectToAction(nameof(Users));
 }
 [Authorize(Roles=Roles.Admin),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> ResetUserPassword(string id,string newPassword){var u=await userManager.FindByIdAsync(id);if(u==null)return NotFound();var token=await userManager.GeneratePasswordResetTokenAsync(u);var r=await userManager.ResetPasswordAsync(u,token,newPassword);TempData[r.Succeeded?"Success":"Error"]=r.Succeeded?"رمز عبور تغییر کرد.":string.Join(" | ",r.Errors.Select(x=>x.Description));return RedirectToAction(nameof(Users));}
 [Authorize(Roles=Roles.Admin),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> UnlockUser(string id){var u=await userManager.FindByIdAsync(id);if(u==null)return NotFound();await userManager.SetLockoutEndDateAsync(u,null);await userManager.ResetAccessFailedCountAsync(u);TempData["Success"]="قفل حساب باز شد.";return RedirectToAction(nameof(Users));}
 [Authorize(Roles=Roles.Admin)] public IActionResult AuditLog()=>View(store.Audit);
 [Authorize(Roles=Roles.Admin)] public IActionResult Settings()=>View();
 [Authorize(Roles=Roles.Admin)] public async Task<IActionResult> DataCore(){ViewBag.Customers=await db.CrmCustomers.CountAsync();ViewBag.Leads=await db.CrmLeads.CountAsync();ViewBag.Deals=await db.CrmDeals.CountAsync();ViewBag.Audits=await db.CrmAuditEvents.CountAsync();return View();}

 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public IActionResult Quotes()=>View(store.Quotes);
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public IActionResult Products()=>View(store.Products);
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public async Task<IActionResult> Forecast(){var deals=await db.CrmDeals.AsNoTracking().ToListAsync();var now=DateTime.UtcNow;var targets=await db.CrmSalesTargets.AsNoTracking().Where(x=>x.Year==now.Year&&x.Month==now.Month&&!x.IsDeleted).ToListAsync();ViewBag.Pipeline=deals.Where(x=>x.Stage!="Won"&&x.Stage!="Lost").Sum(x=>x.Value);ViewBag.Weighted=deals.Where(x=>x.Stage!="Won"&&x.Stage!="Lost").Sum(x=>x.Value*x.Probability/100m);ViewBag.Won=deals.Where(x=>x.Stage=="Won").Sum(x=>x.Value);ViewBag.Commit=deals.Where(x=>x.Stage=="Negotiation").Sum(x=>x.Value);ViewBag.Target=targets.Sum(x=>x.TargetAmount);ViewBag.Stretch=targets.Sum(x=>x.StretchAmount);return View("SqlForecast",deals);}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> SaveSalesTarget(string owner,int year,int month,decimal targetAmount,decimal stretchAmount){var row=await db.CrmSalesTargets.FirstOrDefaultAsync(x=>x.Owner==owner&&x.Year==year&&x.Month==month);if(row==null){row=new SalesTargetEntity{Owner=owner,Year=year,Month=month,CreatedBy=User.Identity?.Name};db.CrmSalesTargets.Add(row);}row.TargetAmount=targetAmount;row.StretchAmount=stretchAmount;row.UpdatedAtUtc=DateTime.UtcNow;row.UpdatedBy=User.Identity?.Name;await db.SaveChangesAsync();await WriteAudit("TargetUpsert","SalesTarget",row.Id.ToString(),owner);return RedirectToAction(nameof(Forecast));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Marketing+","+Roles.Support)] public IActionResult Automations()=>View(store.Automations);
 public IActionResult Knowledge()=>View(store.Knowledge);
 public IActionResult CommandCenter()=>View();
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> CustomerTimeline(int id){var c=await db.CrmCustomers.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id);if(c==null)return NotFound();if(!await CanManageScoped(c.Owner,c.TeamKey))return Forbid();ViewBag.Customer=c;return View(await db.CrmActivities.AsNoTracking().Where(x=>x.EntityType=="Customer"&&x.EntityId==id).OrderByDescending(x=>x.OccurredAtUtc).ToListAsync());}
 public async Task<IActionResult> Customer360(int? id){var access=await GetAccessAsync();var q=ApplyScope(db.CrmCustomers.AsNoTracking(),access);var c=id.HasValue?await q.FirstOrDefaultAsync(x=>x.Id==id.Value):await q.OrderByDescending(x=>x.Score).FirstOrDefaultAsync();if(c==null)return RedirectToAction(nameof(Customers));var model=new Customer(c.Id,c.Name,c.Company,c.Email,c.Phone,c.Segment,c.Owner,c.Status,c.Score);ViewBag.Deals=await ApplyScope(db.CrmDeals.AsNoTracking(),access).Where(x=>x.Customer==c.Company).Select(x=>new Deal(x.Id,x.Title,x.Customer,x.Owner,x.Value,x.Stage,x.Probability,x.CloseDate)).ToListAsync();ViewBag.Contacts=store.Contacts.Where(x=>x.CustomerId==c.Id).ToList();ViewBag.Notes=store.Notes.Where(x=>x.CustomerId==c.Id).ToList();return View(model);}
 [Authorize(Roles=Roles.Admin)] public IActionResult Permissions()=>View(store.Permissions);
 [Authorize(Roles=Roles.Admin)] public IActionResult DataManagement()=>View(store.Imports);
 [Authorize(Roles=Roles.Admin)] public IActionResult Integrations()=>View(store.ApiKeys);
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public IActionResult RevenueIntelligence()=>View(store.Deals);
 [Authorize(Roles=Roles.Admin)] public IActionResult SecurityCenter()=>View();
 [Authorize(Roles=Roles.Admin)] public async Task<IActionResult> AdminHub(){
  var users=userManager.Users.ToList(); ViewBag.TotalUsers=users.Count; ViewBag.ActiveUsers=users.Count(x=>x.IsActive); ViewBag.LockedUsers=users.Count(x=>x.LockoutEnd>DateTimeOffset.UtcNow); ViewBag.RolesCount=roleManager.Roles.Count(); ViewBag.OpenTickets=store.Tickets.Count(x=>x.Status!="حل شده"); ViewBag.Automations=store.Automations.Count(x=>x.Enabled); return View();
 }
 public async Task<IActionResult> AiCopilot(){var access=await GetAccessAsync();var q=ApplyScope(db.CrmDeals.AsNoTracking(),access);var deals=await q.ToListAsync();var lq=ApplyScope(db.CrmLeads.AsNoTracking(),access);var leads=await lq.ToListAsync();ViewBag.Pipeline=deals.Where(x=>x.Stage!="Won"&&x.Stage!="Lost").Sum(x=>x.Value);ViewBag.Weighted=deals.Where(x=>x.Stage!="Won"&&x.Stage!="Lost").Sum(x=>x.Value*x.Probability/100m);ViewBag.HotLeads=leads.Count(x=>x.Score>=80);ViewBag.RiskyDeals=deals.Count(x=>x.Stage!="Won"&&x.Stage!="Lost"&&x.Probability<60);ViewBag.UrgentTickets=store.Tickets.Count(x=>x.Priority=="فوری"&&x.Status!="حل شده");return View(deals.Select(x=>new Deal(x.Id,x.Title,x.Customer,x.Owner,x.Value,x.Stage,x.Probability,x.CloseDate)).ToList());}
 [Authorize(Roles=Roles.Admin)] public async Task<IActionResult> Teams(){ViewBag.Members=await db.CrmTeamMembers.AsNoTracking().Where(x=>!x.IsDeleted).ToListAsync();ViewBag.Users=await userManager.Users.Where(x=>x.IsActive).OrderBy(x=>x.DisplayName).ToListAsync();return View(await db.CrmTeams.AsNoTracking().Where(x=>!x.IsDeleted).OrderBy(x=>x.Name).ToListAsync());}
 [Authorize(Roles=Roles.Admin),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> CreateTeam(string teamKey,string name,string department,string managerUserName){if(string.IsNullOrWhiteSpace(teamKey)||string.IsNullOrWhiteSpace(name))return RedirectToAction(nameof(Teams));if(await db.CrmTeams.AnyAsync(x=>x.TeamKey==teamKey)){TempData["Error"]="Team key already exists.";return RedirectToAction(nameof(Teams));}db.CrmTeams.Add(new CrmTeamEntity{TeamKey=teamKey.Trim().ToLowerInvariant(),Name=name,Department=department??"Sales",ManagerUserName=managerUserName??"",CreatedBy=User.Identity?.Name});await db.SaveChangesAsync();return RedirectToAction(nameof(Teams));}
 [Authorize(Roles=Roles.Admin),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> AddTeamMember(int teamId,string userName,string accessScope){if(!new[]{"Own","Team","All"}.Contains(accessScope))accessScope="Own";var row=await db.CrmTeamMembers.FirstOrDefaultAsync(x=>x.TeamId==teamId&&x.UserName==userName);if(row==null)db.CrmTeamMembers.Add(new CrmTeamMemberEntity{TeamId=teamId,UserName=userName,AccessScope=accessScope,CreatedBy=User.Identity?.Name});else{row.AccessScope=accessScope;row.IsDeleted=false;row.UpdatedAtUtc=DateTime.UtcNow;}await db.SaveChangesAsync();return RedirectToAction(nameof(Teams));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public IActionResult Approvals()=>View(store.Approvals);
 [Authorize(Roles=Roles.Admin)] public IActionResult Sessions()=>View(store.Sessions);
 [Authorize(Roles=Roles.Admin)] public IActionResult FeatureFlags()=>View(store.FeatureFlags);
 [Authorize(Roles=Roles.Admin)] public IActionResult AccessStudio()=>View(store.UserPermissions);
 [Authorize(Roles=Roles.Admin)] public async Task<IActionResult> AccessHealth(){ var users=userManager.Users.ToList(); ViewBag.Total=users.Count; ViewBag.Inactive=users.Count(x=>!x.IsActive); ViewBag.Locked=users.Count(x=>x.LockoutEnd>DateTimeOffset.UtcNow); ViewBag.NoRecentLogin=users.Count(x=>x.LastLoginAtUtc==null || x.LastLoginAtUtc<DateTime.UtcNow.AddDays(-30)); ViewBag.HighRisk=store.UserPermissions.Count(x=>x.Delete||x.Approve||x.Scope=="All"); return View(store.UserPermissions); }
 [Authorize(Roles=Roles.Admin)] public IActionResult DataQuality()=>View(store.Duplicates);
 [Authorize(Roles=Roles.Admin)] public IActionResult IntegrationMonitor()=>View(store.WebhookDeliveries);
 public IActionResult SmartScoring()=>View(store.SmartScores);
 public IActionResult SavedViews()=>View(store.SavedViews);
 [Authorize(Roles=Roles.Admin),HttpPost,ValidateAntiForgeryToken] public IActionResult SavePermission(int id,bool view,bool create,bool edit,bool delete,bool export,bool approve,string scope){
  var i=store.UserPermissions.FindIndex(x=>x.Id==id); if(i<0)return NotFound(); var old=store.UserPermissions[i];
  store.UserPermissions[i]=old with {View=view,Create=create,Edit=edit,Delete=delete,Export=export,Approve=approve,Scope=scope,UpdatedBy=User.Identity?.Name??"Admin",UpdatedAt="همین حالا"};
  TempData["Success"]="دسترسی کاربر بروزرسانی شد."; return RedirectToAction(nameof(AccessStudio));
 }
 [Authorize(Roles=Roles.Admin)] public IActionResult AiAgents()=>View(store.AiAgents);
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Support+","+Roles.Marketing)] public IActionResult Playbooks()=>View(store.Playbooks);
 [Authorize(Roles=Roles.Admin+","+Roles.Support)] public IActionResult SlaPolicies()=>View(store.SlaPolicies);
 [Authorize(Roles=Roles.Admin)] public IActionResult DashboardBuilder()=>View(store.DashboardWidgets);
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public IActionResult ExecutiveCockpit(){ ViewBag.Pipeline=store.Deals.Where(x=>x.Stage!="برنده").Sum(x=>x.Value); ViewBag.Weighted=store.Deals.Where(x=>x.Stage!="برنده").Sum(x=>x.Value*x.Probability/100m); ViewBag.HotLeads=store.Leads.Count(x=>x.Score>=80); ViewBag.OpenTickets=store.Tickets.Count(x=>x.Status!="حل شده"); return View(store.Deals); }
 public IActionResult AiInsights(){
  var audience=User.IsInRole(Roles.Admin)?"Admin":User.IsInRole(Roles.Support)?"Support":User.IsInRole(Roles.Marketing)?"Marketing":"Sales";
  return View(store.AiInsights.Where(x=>x.Audience==audience||User.IsInRole(Roles.Admin)).ToList());
 }

 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public async Task<IActionResult> WinLossAnalytics(){var access=await GetAccessAsync();var deals=await ApplyScope(db.CrmDeals.AsNoTracking(),access).Where(x=>x.Stage=="Won"||x.Stage=="Lost").OrderByDescending(x=>x.ClosedAtUtc).ToListAsync();ViewBag.Won=deals.Count(x=>x.Stage=="Won");ViewBag.Lost=deals.Count(x=>x.Stage=="Lost");ViewBag.WinRate=deals.Count==0?0:Math.Round(100m*deals.Count(x=>x.Stage=="Won")/deals.Count,1);ViewBag.WonValue=deals.Where(x=>x.Stage=="Won").Sum(x=>x.Value);return View(deals);}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public async Task<IActionResult> DuplicateDetection(){var customers=await db.CrmCustomers.AsNoTracking().ToListAsync();var leads=await db.CrmLeads.AsNoTracking().ToListAsync();ViewBag.CustomerGroups=customers.GroupBy(x=>(x.Email??"").Trim().ToLower()).Where(g=>g.Key!=""&&g.Count()>1).Select(g=>g.ToList()).ToList();ViewBag.LeadGroups=leads.GroupBy(x=>((x.Name??"").Trim().ToLower(),(x.Company??"").Trim().ToLower())).Where(g=>g.Count()>1).Select(g=>g.ToList()).ToList();return View();}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> ExportSalesCsv(string entity="deals"){var access=await GetAccessAsync();var sb=new StringBuilder();if(entity=="customers"){sb.AppendLine("Id,Name,Company,Email,Owner,Team,Status,Score");foreach(var x in await ApplyScope(db.CrmCustomers.AsNoTracking(),access).ToListAsync())sb.AppendLine(Csv(x.Id,x.Name,x.Company,x.Email,x.Owner,x.TeamKey,x.Status,x.Score));}else if(entity=="leads"){sb.AppendLine("Id,Name,Company,Source,Owner,Team,Status,Score");foreach(var x in await ApplyScope(db.CrmLeads.AsNoTracking(),access).ToListAsync())sb.AppendLine(Csv(x.Id,x.Name,x.Company,x.Source,x.Owner,x.TeamKey,x.Status,x.Score));}else{sb.AppendLine("Id,Title,Customer,Owner,Team,Value,Stage,Probability,OutcomeReason");foreach(var x in await ApplyScope(db.CrmDeals.AsNoTracking(),access).ToListAsync())sb.AppendLine(Csv(x.Id,x.Title,x.Customer,x.Owner,x.TeamKey,x.Value,x.Stage,x.Probability,x.OutcomeReason));}return File(new UTF8Encoding(true).GetBytes(sb.ToString()),"text/csv",$"ashkan-crm-{entity}-{DateTime.UtcNow:yyyyMMdd}.csv");}
 public async Task<IActionResult> NextBestActions(){var access=await GetAccessAsync();var deals=await ApplyScope(db.CrmDeals.AsNoTracking(),access).Where(x=>x.Stage!="Won"&&x.Stage!="Lost").ToListAsync();var tasks=await ApplyScope(db.CrmTasks.AsNoTracking().Where(x=>!x.IsDeleted&&x.Status!="Done"),access).ToListAsync();var result=deals.Select(d=>new NextBestActionVm{DealId=d.Id,DealTitle=d.Title,Priority=(d.Probability>=70?100:60)+(d.Value>=1000000000m?20:0),Action=d.Probability>=70?"Schedule closing call":"Create next follow-up",Reason=d.Probability>=70?"High-probability opportunity should have a concrete close plan.":"Pipeline opportunity needs a documented next step."}).OrderByDescending(x=>x.Priority).Take(12).ToList();ViewBag.OverdueTasks=tasks.Count(x=>x.DueAtUtc<DateTime.UtcNow);return View(result);}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> ProcessReminders(){await ProcessDueReminders();return RedirectToAction(nameof(Notifications));}
 private sealed record AccessCtx(string Scope,string UserName,string[] TeamKeys);
 private async Task<AccessCtx> GetAccessAsync(){var u=User.Identity?.Name??"";if(User.IsInRole(Roles.Admin))return new("All",u,[]);var memberships=await (from m in db.CrmTeamMembers.AsNoTracking() join t in db.CrmTeams.AsNoTracking() on m.TeamId equals t.Id where m.UserName==u&&!m.IsDeleted&&!t.IsDeleted&&t.IsActive select new{m.AccessScope,t.TeamKey}).ToListAsync();var scope=memberships.Any(x=>x.AccessScope=="All")?"All":memberships.Any(x=>x.AccessScope=="Team")?"Team":"Own";return new(scope,u,memberships.Select(x=>x.TeamKey).Distinct().ToArray());}
 private static IQueryable<CustomerEntity> ApplyScope(IQueryable<CustomerEntity> q,AccessCtx a)=>a.Scope=="All"?q:a.Scope=="Team"?q.Where(x=>a.TeamKeys.Contains(x.TeamKey)):q.Where(x=>x.Owner==a.UserName);
 private static IQueryable<LeadEntity> ApplyScope(IQueryable<LeadEntity> q,AccessCtx a)=>a.Scope=="All"?q:a.Scope=="Team"?q.Where(x=>a.TeamKeys.Contains(x.TeamKey)):q.Where(x=>x.Owner==a.UserName);
 private static IQueryable<DealEntity> ApplyScope(IQueryable<DealEntity> q,AccessCtx a)=>a.Scope=="All"?q:a.Scope=="Team"?q.Where(x=>a.TeamKeys.Contains(x.TeamKey)):q.Where(x=>x.Owner==a.UserName);
 private static IQueryable<CrmTaskEntity> ApplyScope(IQueryable<CrmTaskEntity> q,AccessCtx a)=>a.Scope=="All"?q:a.Scope=="Team"?q.Where(x=>a.TeamKeys.Contains(x.TeamKey)):q.Where(x=>x.Assignee==a.UserName);
 private async Task<bool> CanManageScoped(string owner,string teamKey){var a=await GetAccessAsync();return a.Scope=="All"||string.Equals(owner,a.UserName,StringComparison.OrdinalIgnoreCase)||(a.Scope=="Team"&&a.TeamKeys.Contains(teamKey));}
 private async Task<string> ResolveTeamKey(string userName){return await (from m in db.CrmTeamMembers.AsNoTracking() join t in db.CrmTeams.AsNoTracking() on m.TeamId equals t.Id where m.UserName==userName&&!m.IsDeleted&&t.IsActive orderby m.IsPrimary descending select t.TeamKey).FirstOrDefaultAsync()??"";}
 private async Task ProcessDueReminders(){var now=DateTime.UtcNow;var due=await db.CrmTasks.Where(x=>!x.IsDeleted&&x.Status!="Done"&&x.ReminderAtUtc!=null&&x.ReminderAtUtc<=now&&(x.LastReminderSentAtUtc==null||x.LastReminderSentAtUtc<x.ReminderAtUtc)).Take(100).ToListAsync();foreach(var t in due){db.CrmNotifications.Add(new NotificationEntity{UserName=t.Assignee,Type="Reminder",Title="Task reminder",Message=t.Title,CreatedBy="ReminderEngine"});t.LastReminderSentAtUtc=now;}if(due.Count>0)await db.SaveChangesAsync();}
 private static string Csv(params object?[] values)=>string.Join(",",values.Select(v=>"\""+(v?.ToString()??"").Replace("\"","\"\"")+"\""));

 [Authorize(Roles=Roles.Admin)] public async Task<IActionResult> SecurityOperations(){ViewBag.Failed24h=await db.CrmLoginAudits.AsNoTracking().CountAsync(x=>!x.Succeeded&&x.CreatedAtUtc>DateTime.UtcNow.AddDays(-1));ViewBag.Success24h=await db.CrmLoginAudits.AsNoTracking().CountAsync(x=>x.Succeeded&&x.CreatedAtUtc>DateTime.UtcNow.AddDays(-1));return View(await db.CrmLoginAudits.AsNoTracking().OrderByDescending(x=>x.CreatedAtUtc).Take(100).ToListAsync());}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager)] public async Task<IActionResult> LeadRouting(){return View(await db.CrmLeadRoutingRules.AsNoTracking().Where(x=>!x.IsDeleted).OrderBy(x=>x.Priority).ToListAsync());}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> CreateRoutingRule(LeadRoutingRuleEntity input){input.Id=0;input.CreatedBy=input.UpdatedBy=User.Identity?.Name;db.CrmLeadRoutingRules.Add(input);await db.SaveChangesAsync();await WriteAudit("Create","LeadRoutingRule",input.Id.ToString(),input.Name);return RedirectToAction(nameof(LeadRouting));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager),HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> AutoRouteLead(int id){var lead=await db.CrmLeads.FirstOrDefaultAsync(x=>x.Id==id);if(lead==null)return NotFound();if(!await CanManageScoped(lead.Owner,lead.TeamKey))return Forbid();var rule=await db.CrmLeadRoutingRules.AsNoTracking().Where(x=>x.IsActive&&!x.IsDeleted&&x.MinScore<=lead.Score&&(x.Source=="*"||x.Source==lead.Source)).OrderBy(x=>x.Priority).FirstOrDefaultAsync();if(rule==null){TempData["Error"]="No matching routing rule.";return RedirectToAction(nameof(Leads));}lead.Owner=rule.AssignTo;lead.TeamKey=rule.TeamKey;lead.UpdatedAtUtc=DateTime.UtcNow;lead.UpdatedBy=User.Identity?.Name;await db.SaveChangesAsync();await WriteAudit("AutoRoute","Lead",id.ToString(),$"{rule.Name} -> {rule.AssignTo}");return RedirectToAction(nameof(Leads));}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> CustomerIntelligence(){var access=await GetAccessAsync();var customers=await ApplyScope(db.CrmCustomers.AsNoTracking(),access).OrderByDescending(x=>x.Score).Take(50).ToListAsync();var deals=await ApplyScope(db.CrmDeals.AsNoTracking(),access).ToListAsync();var result=customers.Select(c=>{var cd=deals.Where(d=>d.Customer==c.Company).ToList();var open=cd.Where(d=>d.Stage!="Won"&&d.Stage!="Lost").Sum(d=>d.Value);var stalled=cd.Count(d=>d.Stage!="Won"&&d.Stage!="Lost"&&d.Probability<50);var health=Math.Clamp(c.Score-(stalled*10)+(cd.Any(d=>d.Stage=="Won")?10:0),0,100);var risk=health<50?"High":health<75?"Medium":"Low";return new CustomerIntelligenceVm{CustomerId=c.Id,Customer=c.Company,HealthScore=health,Risk=risk,OpenPipeline=open,Summary=$"Customer score {c.Score}; {cd.Count} deals; {stalled} low-confidence open deals.",RecommendedAction=risk=="High"?"Schedule an executive check-in and review open risks.":open>0?"Confirm the next milestone for active opportunities.":"Create a value-based expansion follow-up."};}).ToList();return View(result);}
 [Authorize(Roles=Roles.Admin+","+Roles.SalesManager+","+Roles.Sales)] public async Task<IActionResult> AiOperations(string? q=null){var access=await GetAccessAsync();var deals=await ApplyScope(db.CrmDeals.AsNoTracking(),access).Where(x=>x.Stage!="Won"&&x.Stage!="Lost").OrderByDescending(x=>x.Value).Take(20).ToListAsync();var leads=await ApplyScope(db.CrmLeads.AsNoTracking(),access).OrderByDescending(x=>x.Score).Take(20).ToListAsync();ViewBag.Query=q;ViewBag.Answer=string.IsNullOrWhiteSpace(q)?"Ask about pipeline risk, hot leads, or next actions.":BuildAiAnswer(q,deals,leads);ViewBag.Deals=deals;ViewBag.Leads=leads;return View();}
 private static string BuildAiAnswer(string q,List<DealEntity> deals,List<LeadEntity> leads){var t=q.ToLowerInvariant();if(t.Contains("risk")||t.Contains("ریسک")){var r=deals.Where(x=>x.Probability<50).OrderByDescending(x=>x.Value).Take(3).Select(x=>$"{x.Title} ({x.Probability}%)");return "Priority risks: "+string.Join("; ",r);}if(t.Contains("lead")||t.Contains("سرنخ")){return "Top leads: "+string.Join("; ",leads.Take(5).Select(x=>$"{x.Name} / {x.Company} ({x.Score})"));}var pipeline=deals.Sum(x=>x.Value);var weighted=deals.Sum(x=>x.Value*x.Probability/100m);return $"Open pipeline: {pipeline:N0}; weighted: {weighted:N0}. Highest-value next focus: "+(deals.FirstOrDefault()?.Title??"No open deal")+".";}
 [Authorize(Roles=Roles.Admin)] public async Task<IActionResult> DataGovernance(){ViewBag.Customers=await db.CrmCustomers.IgnoreQueryFilters().CountAsync();ViewBag.Leads=await db.CrmLeads.IgnoreQueryFilters().CountAsync();ViewBag.Deals=await db.CrmDeals.IgnoreQueryFilters().CountAsync();ViewBag.Audit=await db.CrmAuditEvents.CountAsync();ViewBag.OldAudit=await db.CrmAuditEvents.CountAsync(x=>x.CreatedAtUtc<DateTime.UtcNow.AddDays(-365));return View();}
 [Authorize(Roles=Roles.Admin)] public async Task<IActionResult> BackupExport(){var payload=new{exportedAtUtc=DateTime.UtcNow,customers=await db.CrmCustomers.IgnoreQueryFilters().AsNoTracking().ToListAsync(),leads=await db.CrmLeads.IgnoreQueryFilters().AsNoTracking().ToListAsync(),deals=await db.CrmDeals.IgnoreQueryFilters().AsNoTracking().ToListAsync(),tasks=await db.CrmTasks.AsNoTracking().ToListAsync(),teams=await db.CrmTeams.AsNoTracking().ToListAsync()};var json=System.Text.Json.JsonSerializer.Serialize(payload,new System.Text.Json.JsonSerializerOptions{WriteIndented=true});return File(Encoding.UTF8.GetBytes(json),"application/json",$"ashkan-crm-backup-{DateTime.UtcNow:yyyyMMdd-HHmm}.json");}

}
