namespace AshkanCRM.Models;
public record CrmUser(int Id,string Name,string Email,string Password,string Role,string Department,string Initials);
public record Customer(int Id,string Name,string Company,string Email,string Phone,string Segment,string Owner,string Status,int Score);
public record Deal(int Id,string Title,string Customer,string Owner,decimal Value,string Stage,int Probability,string CloseDate);
public record TaskItem(int Id,string Title,string Assignee,string Priority,string Due,string Status,string Type);
public record Ticket(int Id,string Subject,string Customer,string Priority,string Status,string Assignee,string Updated);
public record Lead(int Id,string Name,string Company,string Source,string Owner,string Status,int Score,string LastContact);
public record ActivityItem(int Id,string Type,string Title,string RelatedTo,string Owner,string When,string Status);
public record NotificationItem(int Id,string Title,string Detail,string Time,bool IsRead,string Audience);
public record AuditItem(int Id,string User,string Action,string Entity,string Detail,string Time);
public static class Roles { public const string Admin="Admin"; public const string SalesManager="SalesManager"; public const string Sales="Sales"; public const string Support="Support"; public const string Marketing="Marketing"; }
public record ProductItem(int Id,string Name,string Sku,string Category,decimal Price,string Status,int Stock);
public record QuoteItem(int Id,string Number,string Customer,string Owner,decimal Amount,string Status,string ValidUntil);
public record AutomationRule(int Id,string Name,string Trigger,string Action,string Owner,bool Enabled,int Runs);
public record KnowledgeArticle(int Id,string Title,string Category,string Author,string Updated,int Views,string Status);
public record GoalItem(int Id,string Owner,string Metric,decimal Target,decimal Actual,string Period);
public record ContactItem(int Id,int CustomerId,string Name,string JobTitle,string Email,string Phone,bool Primary);
public record NoteItem(int Id,int CustomerId,string Author,string Body,string Time,string Visibility);
public record PermissionItem(string Role,string Module,bool View,bool Create,bool Edit,bool Delete,bool Export);
public record ImportJob(int Id,string FileName,string Entity,string Owner,string Status,int Total,int Success,int Failed,string Created);
public record ApiKeyItem(int Id,string Name,string Prefix,string Scope,string Owner,string LastUsed,string Status);
public record TeamItem(int Id,string Name,string Department,string Manager,int Members,string Scope,string Status);
public record ApprovalItem(int Id,string Title,string Type,string RequestedBy,string Approver,string Created,string Status,string Priority);
public record SessionItem(int Id,string User,string Device,string Location,string Ip,string LastActive,string Status);
public record AiInsightItem(int Id,string Area,string Title,string Detail,string Severity,string SuggestedAction,string Audience);
public record FeatureFlagItem(int Id,string Key,string Name,bool Enabled,string Audience,string UpdatedBy);
public record UserPermissionGrant(int Id,string UserEmail,string Module,bool View,bool Create,bool Edit,bool Delete,bool Export,bool Approve,string Scope,string UpdatedBy,string UpdatedAt);
public record SmartScoreItem(int Id,string Entity,string Name,int Score,string Band,string Reason,string SuggestedAction);
public record DuplicateCandidate(int Id,string Entity,string Primary,string Candidate,int Confidence,string Status);
public record WebhookDelivery(int Id,string Endpoint,string Event,string Status,int Attempts,string LastAttempt);
public record SavedViewItem(int Id,string Name,string Module,string Owner,string Filter,bool Shared);
public record AiAgentItem(int Id,string Name,string Purpose,string Audience,string Mode,string Status,int Runs,string LastRun);
public record PlaybookItem(int Id,string Name,string Module,string Trigger,string Steps,string Owner,string Status,int Adoption);
public record SlaPolicyItem(int Id,string Name,string AppliesTo,string FirstResponse,string Resolution,string Escalation,string Status);
public record DashboardWidgetItem(int Id,string Name,string Category,string Audience,bool Enabled,string Size);
